# Generated by Django 5.1.7 on 2025-08-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='nombre_corto',
            field=models.CharField(blank=True, help_text="Nombre corto para mostrar en el calendario (ej: 'D' para 'Día', 'N' para 'Noche')", max_length=10, null=True),
        ),
    ]
