# Generated by Django 5.1.7 on 2025-08-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_estado_nombre_corto'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='es_predeterminado',
            field=models.BooleanField(default=False, help_text='Si es True, este será el estado por defecto cuando no haya asignaciones'),
        ),
        migrations.AddConstraint(
            model_name='estado',
            constraint=models.CheckConstraint(condition=models.Q(('es_predeterminado', False), ('es_predeterminado', True), _connector='OR'), name='solo_un_estado_predeterminado'),
        ),
    ]
