# Generated by Django 5.1.7 on 2025-08-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_add_es_predeterminado_to_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciamedicaporpersonal',
            name='fecha_fin_licencia',
            field=models.DateField(help_text='Fecha de fin de la licencia médica'),
        ),
    ]
